version: '2'

services:
    db:
        image: mysql
        volumes:
            - "${DOCUMENT_PATH}/.data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    php:
        build: php7-fpm
        ports:
            - 9000:9000
        volumes:
            - ${PROJECT_APP_PATH}:/var/www/${PROJECT_NAME}
            - ${DOCUMENT_PATH}/logs/${PROJECT_NAME}:/var/www/${PROJECT_NAME}/app/logs
    nginx:
        build: nginx
        ports:
            - 80:80
        volumes_from:
            - php
        volumes:
            - ${DOCUMENT_PATH}/logs/nginx/:/var/log/nginx
    elk:
        image: willdurand/elk
        ports:
            - 81:80
        volumes:
            - ${DOCUMENT_PATH}/elk/logstash:/opt/elk/logstash
            - ${DOCUMENT_PATH}/elk/logstash/patterns:/opt/elk/logstash/patterns
            - ${DOCUMENT_PATH}/logs/${PROJECT_NAME}:/opt/elk/${PROJECT_NAME}
            - ${DOCUMENT_PATH}/logs/nginx:/opt/elk/nginx
        volumes_from:
            - php
            - nginx
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
